services:
  pg:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: openconf
      POSTGRES_USER: openconf
      POSTGRES_DB: openconf
    ports:
      - "5432:5432"
  bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "../config.docker.yaml:/app/config.yaml"
volumes:
  data: